#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.5f1_d691e07d38ef"
#define UNITY_VERSION_FULL_NICE "2019.3.5f1 (d691e07d38ef)"
#define UNITY_VERSION_BLD 14062048
#define UNITY_VERSION_DATE 1583411660
#define UNITY_VERSION_WIN "2019.3.5.14062048"
#define UNITY_VERSION_BRANCH "2019.3/staging"
